# IsaacLab/docker/docker-compose.binds.yaml
services:
  isaac-lab-base:
    volumes:
      - type: bind
        source: ../../ext_rsl_rl
        target: /workspace/external/ext_rsl_rl
      - type: bind
        source: ../../skrl
        target: /workspace/external/skrl
      - type: bind
        source: ../../isaac_so_arm101
        target: /workspace/external/isaac_so_arm101
  isaac-lab-ros2:
    volumes:
      - type: bind
        source: ../../ext_rsl_rl
        target: /workspace/external/ext_rsl_rl
      - type: bind
        source: ../../skrl
        target: /workspace/external/skrl
      - type: bind
        source: ../../isaac_so_arm101
        target: /workspace/external/isaac_so_arm101
